name: 01 - Matrix Strategy Demo

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Matrix Information
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Matrix Python Version: ${{ matrix.python-version }}"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Execute Application
        run: |
          python app.py &
          APP_PID=$!

          sleep 5

          curl --fail http://127.0.0.1:5000/health

          echo "Application executed successfully."

          echo "Matrix Python Version : ${{ matrix.python-version }}"
          python --version

          kill $APP_PID