name: Docker Build & Push (Composite Action)

on:
  workflow_dispatch:

jobs:
  docker-build-push-job:
    name: Docker Build & Push (Composite Action)

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
      IMAGE_TAG: ${{ github.run_number }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Build & Push Docker Image
        uses: ./.github/actions/docker-build-push
        with:
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          image-name: ${{ env.IMAGE_NAME }}
          image-tag: ${{ env.IMAGE_TAG }}