name: 01 - Caching Demo

on:
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Restore Pip Cache
        id: pip-cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Display Cache Status
        run: |
          echo "Cache Hit: ${{ steps.pip-cache.outputs.cache-hit }}"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

  test-job:
    runs-on: ubuntu-latest

    needs:
      - build-job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Restore Pip Cache
        id: pip-cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Display Cache Status
        run: |
          echo "Cache Hit: ${{ steps.pip-cache.outputs.cache-hit }}"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt